[package]
name = "aria-remote-storage"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
aria-domain = { path = "../domain" }
aria-library = { path = "../library" }
async-trait.workspace = true
chrono.workspace = true
dirs.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["fs", "io-util"] }
tracing.workspace = true
url.workspace = true
walkdir.workspace = true
